runtime: nodejs14
entrypoint: 'node dist/index.js --l1_provider_url $L1_PROVIDER_URL --port $PORT --l2_provider_url $L2_PROVIDER_URL --l2_resolver_address $L2_RESOLVER_ADDRESS --l1_chain_id $L1_CHAIN_ID --l2_chain_id $L2_CHAIN_ID'
env_variables:
  PORT: 8080
  L2_RESOLVER_ADDRESS: '0x470B48eE90Cec0eb6834B986fEA4F3698C986AC4'
  L1_CHAIN_ID: 5
  L2_CHAIN_ID: 420
includes:
  - secret.yaml
